# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CL_Category' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CL_Category

  pod 'MJExtension'
  pod 'AFNetworking'
  pod 'Masonry'
  pod 'FMDB'
  pod 'SDWebImage'

end
